# pylint: skip-file
"""empty message

Revision ID: 437a95a9f2ec
Revises: 
Create Date: 2022-04-14 21:20:51.048052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "437a95a9f2ec"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post_tags")
    op.drop_table("tags")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('tags_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("slug", sa.VARCHAR(length=90), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=90), autoincrement=False, nullable=False),
        sa.Column("summary", sa.TEXT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="tags_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "post_tags",
        sa.Column("post_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("tag_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.id"], name="post_tags_post_id_fkey"
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], name="post_tags_tag_id_fkey"),
        sa.PrimaryKeyConstraint("post_id", "tag_id", name="post_tags_pkey"),
    )
    # ### end Alembic commands ###
