"""empty message

Revision ID: 59637b359350
Revises: b6f54b564054
Create Date: 2021-10-24 10:19:59.473621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59637b359350'
down_revision = 'b6f54b564054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('name', sa.String(length=90), nullable=False))
    op.add_column('posts', sa.Column('content', sa.Text(), nullable=True))
    op.drop_index('ix_posts_title', table_name='posts')
    op.drop_column('posts', 'contents')
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.VARCHAR(length=90), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('contents', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('ix_posts_title', 'posts', ['title'], unique=False)
    op.drop_column('posts', 'content')
    op.drop_column('posts', 'name')
    # ### end Alembic commands ###
