"""empty message

Revision ID: 781854c48dc8
Revises: 59637b359350
Create Date: 2021-10-24 10:23:12.689920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781854c48dc8'
down_revision = '59637b359350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('last_edit_date', sa.DateTime(), nullable=False),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.String(length=270), nullable=True),
    sa.Column('name', sa.String(length=90), nullable=False),
    sa.Column('slug', sa.String(length=90), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('parent_category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_category'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_categories',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
