"""empty message

Revision ID: b6f54b564054
Revises: b9f7b3cf6036
Create Date: 2021-10-24 09:58:45.901384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f54b564054'
down_revision = 'b9f7b3cf6036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_slug', table_name='posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_posts_slug', 'posts', ['slug'], unique=False)
    # ### end Alembic commands ###
