"""empty message

Revision ID: b9f7b3cf6036
Revises: 085d90d3eaa7
Create Date: 2021-10-24 08:46:35.954779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9f7b3cf6036'
down_revision = '085d90d3eaa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('last_edit_date', sa.DateTime(), nullable=False),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=90), nullable=False),
    sa.Column('summary', sa.String(length=270), nullable=True),
    sa.Column('contents', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=90), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_slug'), 'posts', ['slug'], unique=False)
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    op.drop_index('ix_wep_entity_slug', table_name='wep_entity')
    op.drop_index('ix_wep_entity_title', table_name='wep_entity')
    op.drop_table('wep_entity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wep_entity',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_edit_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('publication_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=90), autoincrement=False, nullable=False),
    sa.Column('summary', sa.VARCHAR(length=270), autoincrement=False, nullable=True),
    sa.Column('contents', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=90), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='wep_entity_pkey')
    )
    op.create_index('ix_wep_entity_title', 'wep_entity', ['title'], unique=False)
    op.create_index('ix_wep_entity_slug', 'wep_entity', ['slug'], unique=False)
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.drop_index(op.f('ix_posts_slug'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
